/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	examplev1 "github.com/YaoZengzeng/practice/kubernetes-controller-example/pkg/apis/example/v1"
	versioned "github.com/YaoZengzeng/practice/kubernetes-controller-example/pkg/client/clientset/versioned"
	internalinterfaces "github.com/YaoZengzeng/practice/kubernetes-controller-example/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/YaoZengzeng/practice/kubernetes-controller-example/pkg/client/listers/example/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DogInformer provides access to a shared informer and lister for
// Dogs.
type DogInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DogLister
}

type dogInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDogInformer constructs a new informer for Dog type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDogInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDogInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDogInformer constructs a new informer for Dog type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDogInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().Dogs(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().Dogs(namespace).Watch(options)
			},
		},
		&examplev1.Dog{},
		resyncPeriod,
		indexers,
	)
}

func (f *dogInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDogInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dogInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&examplev1.Dog{}, f.defaultInformer)
}

func (f *dogInformer) Lister() v1.DogLister {
	return v1.NewDogLister(f.Informer().GetIndexer())
}
